# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    container_name: postgres_db
    # образ, из которого должен быть запущен контейнер
    image: postgres:14-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
        - POSTGRES_DB=later
        - POSTGRES_USER=later_admin
        - POSTGRES_PASSWORD=admin@aDminNew
    ports:
      - "5435:5432"

  webapp:
    build: .
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_NAME=later
      - POSTGRES_USER=later_admin
      - POSTGRES_PASSWORD=admin@aDmin
      - DB_HOST=db
      - DB_PORT=5432


